// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';

export function GetStatus():Promise<main.AppStatus>;

export function OpenLogFolder():Promise<void>;

export function RunScan(arg1:string):Promise<model.DiagnosticReport>;
