// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAIExplanation(arg1, arg2) {
  return window['go']['main']['App']['GenerateAIExplanation'](arg1, arg2);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAISendPreview(arg1) {
  return window['go']['main']['App']['GetAISendPreview'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListRollbackRecords() {
  return window['go']['main']['App']['ListRollbackRecords']();
}

export function MarkLagNow() {
  return window['go']['main']['App']['MarkLagNow']();
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function RollbackService(arg1, arg2) {
  return window['go']['main']['App']['RollbackService'](arg1, arg2);
}

export function RollbackStartup(arg1, arg2) {
  return window['go']['main']['App']['RollbackStartup'](arg1, arg2);
}

export function RunAction(arg1, arg2) {
  return window['go']['main']['App']['RunAction'](arg1, arg2);
}

export function RunScan(arg1, arg2) {
  return window['go']['main']['App']['RunScan'](arg1, arg2);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}
