// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';

export function GetStatus():Promise<main.AppStatus>;

export function ListRollbackRecords():Promise<Array<model.RollbackRecord>>;

export function OpenLogFolder():Promise<void>;

export function RollbackService(arg1:string,arg2:string):Promise<model.ActionResult>;

export function RunAction(arg1:string,arg2:Record<string, any>):Promise<model.ActionResult>;

export function RunScan(arg1:string):Promise<model.DiagnosticReport>;
