// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function GenerateAIExplanation(arg1:model.DiagnosticReport,arg2:string):Promise<model.AIExplanation>;

export function GetAIConfig():Promise<model.AIConfig>;

export function GetAISendPreview(arg1:model.DiagnosticReport):Promise<string>;

export function GetStatus():Promise<main.AppStatus>;

export function ListRollbackRecords():Promise<Array<model.RollbackRecord>>;

export function MarkLagNow():Promise<number>;

export function OpenLogFolder():Promise<void>;

export function RollbackService(arg1:string,arg2:string):Promise<model.ActionResult>;

export function RollbackStartup(arg1:string,arg2:string):Promise<model.ActionResult>;

export function RunAction(arg1:string,arg2:Record<string, any>):Promise<model.ActionResult>;

export function RunScan(arg1:string,arg2:string):Promise<model.DiagnosticReport>;

export function SaveAIConfig(arg1:model.AIConfig):Promise<void>;
