// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function RunScan(arg1) {
  return window['go']['main']['App']['RunScan'](arg1);
}
